apiVersion: veecode.backstage.io/v1alpha1
kind: Database
metadata:
  name: "rdshomologdemo"
  annotations:
    github.com/project-slug: veecode-homolog/ rdshomologdemo
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
